[target.'cfg(target_arch = "xtensa")']
runner    = "espflash flash --monitor"
rustflags = [
  # GNU LD
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-nostartfiles",

  # LLD
  # "-C", "link-arg=-Tlinkall.x",
  # "-C", "linker=rust-lld",
]

[env]
DEFMT_LOG="debug"

[build]
target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core"]
